<MainScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "30dp"

        MDIconButton:
            icon: "cog"
            pos_hint: {"right": 1, "top": 1}
            icon_size: "50dp"

        MDLabel:
            text: "Shooter"
            haling: "Center"
            fornt_size: "60sp"

        Image:
            source: "accets/images/img.jpg"
            size_hint_y: 0.7
            aloow_stretch: True

        MDButton:
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            on_press:
                root.manager.current = "game"

            MDButtonText:
                text: "PLAY"
                font_size: "80sp"
                theme_text_color: "Custom"
                text_color: "white"

<Ship@Image>:
    source: "assets/images/rocket.jpg"
    size_hint: None, None
    size: dp(100), dp(200)

<GameScreen>:
    FloatLayout:
        FloatLayout:
            id: game

            FloatLayout:
                id: back
                canvas.before:
                    Color:
                        rgba: 0.02, 0.02, 0.08, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size


            FloatLayout:
                id: front
                Ship:
                    id: ship
                    center_x: root.center_x
                    y: dp(120)

        FloatLayout:
            id: interface